---
version: "1.0"
services:

  diffusion-app:
    image: diffusion-app
    build: ./diffusion
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
